from __future__ import annotations

from collections.abc import Iterable, Iterator
from typing import Any, Generic, Protocol, TypeVar, overload

_T_co = TypeVar("_T_co", covariant=True)

class InstrumentedAttribute(Protocol[_T_co]):
    def is_(self, other: object | None) -> Any: ...
    def isnot(self, other: object | None) -> Any: ...
    def in_(self, other: Iterable[_T_co] | Any) -> Any: ...
    def contains(self, other: object, **kw: Any) -> Any: ...
    def like(self, other: str, **kw: Any) -> Any: ...
    def ilike(self, other: str, **kw: Any) -> Any: ...
    def isnot_distinct_from(self, other: object) -> Any: ...
    def is_distinct_from(self, other: object) -> Any: ...
    def asc(self) -> Any: ...
    def desc(self) -> Any: ...
    def label(self, name: str) -> Any: ...

class Pagination(Generic[_T_co]):
    page: int
    per_page: int
    total: int
    items: list[_T_co]

class Query(Generic[_T_co]):
    def __iter__(self) -> Iterator[_T_co]: ...
    def all(self) -> list[_T_co]: ...
    def first(self) -> _T_co | None: ...
    def one(self) -> _T_co: ...
    def one_or_none(self) -> _T_co | None: ...
    def limit(self, n: int) -> Query[_T_co]: ...
    def offset(self, n: int) -> Query[_T_co]: ...
    def filter(self, *criteria: Any) -> Query[_T_co]: ...
    def filter_by(self, **kwargs: Any) -> Query[_T_co]: ...
    def order_by(self, *criteria: Any) -> Query[_T_co]: ...
    def with_entities(self, *entities: Any) -> Query[Any]: ...
    def join(self, *props: Any, **kwargs: Any) -> Query[_T_co]: ...
    def outerjoin(self, *props: Any, **kwargs: Any) -> Query[_T_co]: ...
    def group_by(self, *props: Any) -> Query[_T_co]: ...
    def distinct(self) -> Query[_T_co]: ...
    def count(self) -> int: ...
    def exists(self) -> Any: ...
    def scalar(self) -> Any: ...
    @overload
    def paginate(
        self, page: int | None = ..., per_page: int | None = ..., error_out: bool = ...
    ) -> Pagination[_T_co]: ...
    @overload
    def paginate(
        self, *, page: int | None = ..., per_page: int | None = ..., error_out: bool = ...
    ) -> Pagination[_T_co]: ...

    # Comparison/collection helpers often attached via InstrumentedAttribute
    def contains(self, other: object, **kwargs: Any) -> Any: ...
    def any(self, criterion: object | None = ..., **kwargs: Any) -> Any: ...
    def all_(self) -> Any: ...

# Common aliases used by Flask-SQLAlchemy
BaseQuery = Query
