default_tasks:
  - id: sync_accounts
    trigger_type: cron
    trigger_params:
      second: 0
      minute: 0
      hour: 1

  - id: calculate_account
    trigger_type: cron
    trigger_params:
      second: 0
      minute: 0
      hour: 2

  - id: sync_databases
    trigger_type: cron
    trigger_params:
      second: 0
      minute: 0
      hour: 3

  - id: calculate_database
    trigger_type: cron
    trigger_params:
      second: 0
      minute: 0
      hour: 4

  - id: sync_veeam_backups
    trigger_type: cron
    trigger_params:
      second: 0
      minute: 0
      hour: 5

  - id: sync_cluster_status
    trigger_type: cron
    trigger_params:
      second: 0
      minute: 0
      hour: 6

  - id: email_alert
    trigger_type: cron
    trigger_params:
      second: 0
      minute: 0
      hour: 9
