-- =============================================
-- 权限配置数据初始化脚本
-- 鲸落 - 数据同步管理平台
-- 从现有数据库导出的真实权限配置数据
-- 导出时间: 2025-09-19 08:27:54
-- =============================================

-- 插入权限配置数据
INSERT INTO permission_configs (db_type, category, permission_name, description, is_active, sort_order, created_at, updated_at) VALUES
-- MYSQL权限配置
-- database_privileges
('mysql', 'database_privileges', 'CREATE', '创建数据库和表', TRUE, 1, NOW(), NOW()),
('mysql', 'database_privileges', 'DROP', '删除数据库和表', TRUE, 2, NOW(), NOW()),
('mysql', 'database_privileges', 'ALTER', '修改数据库和表结构', TRUE, 3, NOW(), NOW()),
('mysql', 'database_privileges', 'INDEX', '创建和删除索引', TRUE, 4, NOW(), NOW()),
('mysql', 'database_privileges', 'INSERT', '插入数据', TRUE, 5, NOW(), NOW()),
('mysql', 'database_privileges', 'UPDATE', '更新数据', TRUE, 6, NOW(), NOW()),
('mysql', 'database_privileges', 'DELETE', '删除数据', TRUE, 7, NOW(), NOW()),
('mysql', 'database_privileges', 'SELECT', '查询数据', TRUE, 8, NOW(), NOW()),
('mysql', 'database_privileges', 'CREATE TEMPORARY TABLES', '创建临时表', TRUE, 9, NOW(), NOW()),
('mysql', 'database_privileges', 'LOCK TABLES', '锁定表', TRUE, 10, NOW(), NOW()),
('mysql', 'database_privileges', 'EXECUTE', '执行存储过程和函数', TRUE, 11, NOW(), NOW()),
('mysql', 'database_privileges', 'CREATE VIEW', '创建视图', TRUE, 12, NOW(), NOW()),
('mysql', 'database_privileges', 'SHOW VIEW', '显示视图', TRUE, 13, NOW(), NOW()),
('mysql', 'database_privileges', 'CREATE ROUTINE', '创建存储过程和函数', TRUE, 14, NOW(), NOW()),
('mysql', 'database_privileges', 'ALTER ROUTINE', '修改存储过程和函数', TRUE, 15, NOW(), NOW()),
('mysql', 'database_privileges', 'EVENT', '创建、修改、删除事件', TRUE, 16, NOW(), NOW()),
('mysql', 'database_privileges', 'TRIGGER', '创建和删除触发器', TRUE, 17, NOW(), NOW()),

-- global_privileges
('mysql', 'global_privileges', 'ALTER', '修改表结构', TRUE, 1, NOW(), NOW()),
('mysql', 'global_privileges', 'ALTER ROUTINE', '修改存储过程和函数', TRUE, 2, NOW(), NOW()),
('mysql', 'global_privileges', 'CREATE', '创建数据库和表', TRUE, 3, NOW(), NOW()),
('mysql', 'global_privileges', 'CREATE ROUTINE', '创建存储过程和函数', TRUE, 4, NOW(), NOW()),
('mysql', 'global_privileges', 'CREATE TEMPORARY TABLES', '创建临时表', TRUE, 5, NOW(), NOW()),
('mysql', 'global_privileges', 'CREATE USER', '创建用户权限', TRUE, 6, NOW(), NOW()),
('mysql', 'global_privileges', 'CREATE VIEW', '创建视图', TRUE, 7, NOW(), NOW()),
('mysql', 'global_privileges', 'DELETE', '删除数据', TRUE, 8, NOW(), NOW()),
('mysql', 'global_privileges', 'DROP', '删除数据库和表', TRUE, 9, NOW(), NOW()),
('mysql', 'global_privileges', 'EVENT', '创建、修改、删除事件', TRUE, 10, NOW(), NOW()),
('mysql', 'global_privileges', 'EXECUTE', '执行存储过程和函数', TRUE, 11, NOW(), NOW()),
('mysql', 'global_privileges', 'FILE', '文件操作权限', TRUE, 12, NOW(), NOW()),
('mysql', 'global_privileges', 'GRANT OPTION', '授权权限，可以授予其他用户权限', TRUE, 13, NOW(), NOW()),
('mysql', 'global_privileges', 'INDEX', '创建和删除索引', TRUE, 14, NOW(), NOW()),
('mysql', 'global_privileges', 'INSERT', '插入数据', TRUE, 15, NOW(), NOW()),
('mysql', 'global_privileges', 'LOCK TABLES', '锁定表', TRUE, 16, NOW(), NOW()),
('mysql', 'global_privileges', 'PROCESS', '查看所有进程', TRUE, 17, NOW(), NOW()),
('mysql', 'global_privileges', 'REFERENCES', '引用权限', TRUE, 18, NOW(), NOW()),
('mysql', 'global_privileges', 'RELOAD', '重载权限表', TRUE, 19, NOW(), NOW()),
('mysql', 'global_privileges', 'REPLICATION CLIENT', '复制客户端权限', TRUE, 20, NOW(), NOW()),
('mysql', 'global_privileges', 'REPLICATION SLAVE', '复制从库权限', TRUE, 21, NOW(), NOW()),
('mysql', 'global_privileges', 'SELECT', '查询数据', TRUE, 22, NOW(), NOW()),
('mysql', 'global_privileges', 'SHOW DATABASES', '显示所有数据库', TRUE, 23, NOW(), NOW()),
('mysql', 'global_privileges', 'SHOW VIEW', '显示视图', TRUE, 24, NOW(), NOW()),
('mysql', 'global_privileges', 'SHUTDOWN', '关闭MySQL服务器', TRUE, 25, NOW(), NOW()),
('mysql', 'global_privileges', 'SUPER', '超级权限，可以执行任何操作', TRUE, 26, NOW(), NOW()),
('mysql', 'global_privileges', 'TRIGGER', '创建和删除触发器', TRUE, 27, NOW(), NOW()),
('mysql', 'global_privileges', 'UPDATE', '更新数据', TRUE, 28, NOW(), NOW()),
('mysql', 'global_privileges', 'USAGE', '无权限，仅用于连接', TRUE, 29, NOW(), NOW()),
('mysql', 'global_privileges', 'APPLICATION_PASSWORD_ADMIN', '应用程序密码管理', TRUE, 30, NOW(), NOW()),
('mysql', 'global_privileges', 'AUDIT_ABORT_EXEMPT', '审计中止豁免', TRUE, 31, NOW(), NOW()),
('mysql', 'global_privileges', 'AUDIT_ADMIN', '审计管理', TRUE, 32, NOW(), NOW()),
('mysql', 'global_privileges', 'AUTHENTICATION_POLICY_ADMIN', '身份验证策略管理', TRUE, 33, NOW(), NOW()),
('mysql', 'global_privileges', 'BACKUP_ADMIN', '备份管理', TRUE, 34, NOW(), NOW()),
('mysql', 'global_privileges', 'BINLOG_ADMIN', '二进制日志管理', TRUE, 35, NOW(), NOW()),
('mysql', 'global_privileges', 'BINLOG_ENCRYPTION_ADMIN', '二进制日志加密管理', TRUE, 36, NOW(), NOW()),
('mysql', 'global_privileges', 'CLONE_ADMIN', '克隆管理', TRUE, 37, NOW(), NOW()),
('mysql', 'global_privileges', 'CONNECTION_ADMIN', '连接管理', TRUE, 38, NOW(), NOW()),
('mysql', 'global_privileges', 'CREATE ROLE', '创建角色', TRUE, 39, NOW(), NOW()),
('mysql', 'global_privileges', 'CREATE TABLESPACE', '创建表空间', TRUE, 40, NOW(), NOW()),
('mysql', 'global_privileges', 'DROP ROLE', '删除角色', TRUE, 41, NOW(), NOW()),
('mysql', 'global_privileges', 'ENCRYPTION_KEY_ADMIN', '加密密钥管理', TRUE, 42, NOW(), NOW()),
('mysql', 'global_privileges', 'FIREWALL_EXEMPT', '防火墙豁免', TRUE, 43, NOW(), NOW()),
('mysql', 'global_privileges', 'FLUSH_OPTIMIZER_COSTS', '刷新优化器成本', TRUE, 44, NOW(), NOW()),
('mysql', 'global_privileges', 'FLUSH_STATUS', '刷新状态', TRUE, 45, NOW(), NOW()),
('mysql', 'global_privileges', 'FLUSH_TABLES', '刷新表', TRUE, 46, NOW(), NOW()),
('mysql', 'global_privileges', 'FLUSH_USER_RESOURCES', '刷新用户资源', TRUE, 47, NOW(), NOW()),
('mysql', 'global_privileges', 'GROUP_REPLICATION_ADMIN', '组复制管理', TRUE, 48, NOW(), NOW()),
('mysql', 'global_privileges', 'GROUP_REPLICATION_STREAM', '组复制流', TRUE, 49, NOW(), NOW()),
('mysql', 'global_privileges', 'INNODB_REDO_LOG_ARCHIVE', 'InnoDB重做日志归档', TRUE, 50, NOW(), NOW()),
('mysql', 'global_privileges', 'INNODB_REDO_LOG_ENABLE', 'InnoDB重做日志启用', TRUE, 51, NOW(), NOW()),
('mysql', 'global_privileges', 'PASSWORDLESS_USER_ADMIN', '无密码用户管理', TRUE, 52, NOW(), NOW()),
('mysql', 'global_privileges', 'PERSIST_RO_VARIABLES_ADMIN', '持久化只读变量管理', TRUE, 53, NOW(), NOW()),
('mysql', 'global_privileges', 'REPLICATION_APPLIER', '复制应用器', TRUE, 54, NOW(), NOW()),
('mysql', 'global_privileges', 'REPLICATION_SLAVE_ADMIN', '复制从库管理', TRUE, 55, NOW(), NOW()),
('mysql', 'global_privileges', 'RESOURCE_GROUP_ADMIN', '资源组管理', TRUE, 56, NOW(), NOW()),
('mysql', 'global_privileges', 'RESOURCE_GROUP_USER', '资源组用户', TRUE, 57, NOW(), NOW()),
('mysql', 'global_privileges', 'ROLE_ADMIN', '角色管理', TRUE, 58, NOW(), NOW()),
('mysql', 'global_privileges', 'SENSITIVE_VARIABLES_OBSERVER', '敏感变量观察者', TRUE, 59, NOW(), NOW()),
('mysql', 'global_privileges', 'SERVICE_CONNECTION_ADMIN', '服务连接管理', TRUE, 60, NOW(), NOW()),
('mysql', 'global_privileges', 'SESSION_VARIABLES_ADMIN', '会话变量管理', TRUE, 61, NOW(), NOW()),
('mysql', 'global_privileges', 'SET_USER_ID', '设置用户ID', TRUE, 62, NOW(), NOW()),
('mysql', 'global_privileges', 'SHOW_ROUTINE', '显示例程', TRUE, 63, NOW(), NOW()),
('mysql', 'global_privileges', 'SYSTEM_USER', '系统用户', TRUE, 64, NOW(), NOW()),
('mysql', 'global_privileges', 'SYSTEM_VARIABLES_ADMIN', '系统变量管理', TRUE, 65, NOW(), NOW()),
('mysql', 'global_privileges', 'TABLE_ENCRYPTION_ADMIN', '表加密管理', TRUE, 66, NOW(), NOW()),
('mysql', 'global_privileges', 'TELEMETRY_LOG_ADMIN', '遥测日志管理', TRUE, 67, NOW(), NOW()),
('mysql', 'global_privileges', 'XA_RECOVER_ADMIN', 'XA恢复管理', TRUE, 68, NOW(), NOW()),

-- ORACLE权限配置
-- roles
('oracle', 'roles', 'ADM_PARALLEL_EXECUTE_TASK', '并行执行任务管理角色', TRUE, 1, NOW(), NOW()),
('oracle', 'roles', 'APEX_ADMINISTRATOR_ROLE', 'APEX管理员角色', TRUE, 2, NOW(), NOW()),
('oracle', 'roles', 'AQ_ADMINISTRATOR_ROLE', '高级队列管理员角色', TRUE, 3, NOW(), NOW()),
('oracle', 'roles', 'AQ_USER_ROLE', '高级队列用户角色', TRUE, 4, NOW(), NOW()),
('oracle', 'roles', 'AUDIT_ADMIN', '审计管理员角色', TRUE, 5, NOW(), NOW()),
('oracle', 'roles', 'AUDIT_VIEWER', '审计查看者角色', TRUE, 6, NOW(), NOW()),
('oracle', 'roles', 'AUTHENTICATEDUSER', '认证用户角色', TRUE, 7, NOW(), NOW()),
('oracle', 'roles', 'CDB_DBA', 'CDB数据库管理员角色', TRUE, 8, NOW(), NOW()),
('oracle', 'roles', 'CONNECT', '连接角色', TRUE, 9, NOW(), NOW()),
('oracle', 'roles', 'CTXAPP', '文本应用角色', TRUE, 10, NOW(), NOW()),
('oracle', 'roles', 'DBA', '数据库管理员角色', TRUE, 11, NOW(), NOW()),
('oracle', 'roles', 'DBFS_ROLE', '数据库文件系统角色', TRUE, 12, NOW(), NOW()),
('oracle', 'roles', 'DV_ACCTMGR', '数据库保险库账户管理器角色', TRUE, 13, NOW(), NOW()),
('oracle', 'roles', 'DV_ADMIN', '数据库保险库管理员角色', TRUE, 14, NOW(), NOW()),
('oracle', 'roles', 'DV_AUDIT_CLEANUP', '数据库保险库审计清理角色', TRUE, 15, NOW(), NOW()),
('oracle', 'roles', 'DV_DATAPUMP_EXP_FULL_DATABASE', '数据库保险库数据泵导出完整数据库角色', TRUE, 16, NOW(), NOW()),
('oracle', 'roles', 'DV_DATAPUMP_IMP_FULL_DATABASE', '数据库保险库数据泵导入完整数据库角色', TRUE, 17, NOW(), NOW()),
('oracle', 'roles', 'DV_GATHER_SYSTEM_STATISTICS', '数据库保险库收集系统统计信息角色', TRUE, 18, NOW(), NOW()),
('oracle', 'roles', 'DV_MONITOR', '数据库保险库监控角色', TRUE, 19, NOW(), NOW()),
('oracle', 'roles', 'DV_OWNER', '数据库保险库所有者角色', TRUE, 20, NOW(), NOW()),
('oracle', 'roles', 'DV_PATCH_ADMIN', '数据库保险库补丁管理员角色', TRUE, 21, NOW(), NOW()),
('oracle', 'roles', 'DV_POLICY_OWNER', '数据库保险库策略所有者角色', TRUE, 22, NOW(), NOW()),
('oracle', 'roles', 'DV_PUBLIC', '数据库保险库公共角色', TRUE, 23, NOW(), NOW()),
('oracle', 'roles', 'DV_REALM_OWNER', '数据库保险库领域所有者角色', TRUE, 24, NOW(), NOW()),
('oracle', 'roles', 'DV_REALM_RESOURCE', '数据库保险库领域资源角色', TRUE, 25, NOW(), NOW()),
('oracle', 'roles', 'DV_SECANALYST', '数据库保险库安全分析师角色', TRUE, 26, NOW(), NOW()),
('oracle', 'roles', 'DV_SELECT_CATALOG_ROLE', '数据库保险库选择目录角色', TRUE, 27, NOW(), NOW()),
('oracle', 'roles', 'DV_SITE_ADMIN', '数据库保险库站点管理员角色', TRUE, 28, NOW(), NOW()),
('oracle', 'roles', 'DV_STREAMS_ADMIN', '数据库保险库流管理员角色', TRUE, 29, NOW(), NOW()),
('oracle', 'roles', 'DV_TABLESPACE_QUOTA', '数据库保险库表空间配额角色', TRUE, 30, NOW(), NOW()),
('oracle', 'roles', 'DV_XSTREAM_ADMIN', '数据库保险库XStream管理员角色', TRUE, 31, NOW(), NOW()),
('oracle', 'roles', 'EM_EXPRESS_ALL', '企业管理器Express所有角色', TRUE, 32, NOW(), NOW()),
('oracle', 'roles', 'EM_EXPRESS_BASIC', '企业管理器Express基础角色', TRUE, 33, NOW(), NOW()),
('oracle', 'roles', 'EXECUTE_CATALOG_ROLE', '执行目录角色', TRUE, 34, NOW(), NOW()),
('oracle', 'roles', 'EXP_FULL_DATABASE', '导出完整数据库角色', TRUE, 35, NOW(), NOW()),
('oracle', 'roles', 'GATHER_SYSTEM_STATISTICS', '收集系统统计信息角色', TRUE, 36, NOW(), NOW()),
('oracle', 'roles', 'GLOBAL_AQ_USER_ROLE', '全局高级队列用户角色', TRUE, 37, NOW(), NOW()),
('oracle', 'roles', 'HS_ADMIN_EXECUTE_ROLE', '异构服务管理员执行角色', TRUE, 38, NOW(), NOW()),
('oracle', 'roles', 'HS_ADMIN_ROLE', '异构服务管理员角色', TRUE, 39, NOW(), NOW()),
('oracle', 'roles', 'HS_ADMIN_SELECT_ROLE', '异构服务管理员选择角色', TRUE, 40, NOW(), NOW()),
('oracle', 'roles', 'IMP_FULL_DATABASE', '导入完整数据库角色', TRUE, 41, NOW(), NOW()),
('oracle', 'roles', 'JAVADEBUGPRIV', 'Java调试权限角色', TRUE, 42, NOW(), NOW()),
('oracle', 'roles', 'JAVAUSERPRIV', 'Java用户权限角色', TRUE, 43, NOW(), NOW()),
('oracle', 'roles', 'JAVA_ADMIN', 'Java管理员角色', TRUE, 44, NOW(), NOW()),
('oracle', 'roles', 'JAVA_DEPLOY', 'Java部署角色', TRUE, 45, NOW(), NOW()),
('oracle', 'roles', 'JMXSERVER', 'JMX服务器角色', TRUE, 46, NOW(), NOW()),
('oracle', 'roles', 'LOGSTDBY_ADMINISTRATOR', '逻辑备用数据库管理员角色', TRUE, 47, NOW(), NOW()),
('oracle', 'roles', 'OEM_ADVISOR', 'OEM顾问角色', TRUE, 48, NOW(), NOW()),
('oracle', 'roles', 'OEM_MONITOR', 'OEM监控角色', TRUE, 49, NOW(), NOW()),
('oracle', 'roles', 'OLAP_DBA', 'OLAP数据库管理员角色', TRUE, 50, NOW(), NOW()),
('oracle', 'roles', 'OLAP_USER', 'OLAP用户角色', TRUE, 51, NOW(), NOW()),
('oracle', 'roles', 'OLAP_XS_ADMIN', 'OLAP XS管理员角色', TRUE, 52, NOW(), NOW()),
('oracle', 'roles', 'OLAP_XS_APP_ADMIN', 'OLAP XS应用管理员角色', TRUE, 53, NOW(), NOW()),
('oracle', 'roles', 'OLAP_XS_CACHE_ADMIN', 'OLAP XS缓存管理员角色', TRUE, 54, NOW(), NOW()),
('oracle', 'roles', 'OLAP_XS_SESSION_ADMIN', 'OLAP XS会话管理员角色', TRUE, 55, NOW(), NOW()),
('oracle', 'roles', 'ORDADMIN', 'Oracle多媒体管理员角色', TRUE, 56, NOW(), NOW()),
('oracle', 'roles', 'ORDPLUGINS', 'Oracle多媒体插件角色', TRUE, 57, NOW(), NOW()),
('oracle', 'roles', 'ORDSYS', 'Oracle多媒体系统角色', TRUE, 58, NOW(), NOW()),
('oracle', 'roles', 'PDB_DBA', 'PDB数据库管理员角色', TRUE, 59, NOW(), NOW()),
('oracle', 'roles', 'PLUSTRACE', 'PL/SQL跟踪角色', TRUE, 60, NOW(), NOW()),
('oracle', 'roles', 'RECOVERY_CATALOG_OWNER', '恢复目录所有者角色', TRUE, 61, NOW(), NOW()),
('oracle', 'roles', 'RESOURCE', '资源角色', TRUE, 62, NOW(), NOW()),
('oracle', 'roles', 'SCHEDULER_ADMIN', '调度器管理员角色', TRUE, 63, NOW(), NOW()),
('oracle', 'roles', 'SELECT_CATALOG_ROLE', '选择目录角色', TRUE, 64, NOW(), NOW()),
('oracle', 'roles', 'WM_ADMIN_ROLE', '工作区管理器管理员角色', TRUE, 65, NOW(), NOW()),
('oracle', 'roles', 'XDBADMIN', 'XML数据库管理员角色', TRUE, 66, NOW(), NOW()),
('oracle', 'roles', 'XDB_SET_INVOKER', 'XML数据库设置调用者角色', TRUE, 67, NOW(), NOW()),

-- system_privileges
('oracle', 'system_privileges', 'ADMINISTER ANY SQL TUNING SET', '管理任意SQL调优集', TRUE, 1, NOW(), NOW()),
('oracle', 'system_privileges', 'ADMINISTER DATABASE TRIGGER', '管理数据库触发器', TRUE, 2, NOW(), NOW()),
('oracle', 'system_privileges', 'ADMINISTER RESOURCE MANAGER', '管理资源管理器', TRUE, 3, NOW(), NOW()),
('oracle', 'system_privileges', 'ADMINISTER SQL MANAGEMENT OBJECT', '管理SQL管理对象', TRUE, 4, NOW(), NOW()),
('oracle', 'system_privileges', 'ADMINISTER SQL TUNING SET', '管理SQL调优集', TRUE, 5, NOW(), NOW()),
('oracle', 'system_privileges', 'ADVISOR', '顾问权限', TRUE, 6, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY ASSEMBLY', '修改任意程序集', TRUE, 7, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY CLUSTER', '修改任意集群', TRUE, 8, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY CUBE', '修改任意多维数据集', TRUE, 9, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY CUBE DIMENSION', '修改任意多维数据集维度', TRUE, 10, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY DIMENSION', '修改任意维度', TRUE, 11, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY EDITION', '修改任意版本', TRUE, 12, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY EVALUATION CONTEXT', '修改任意评估上下文', TRUE, 13, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY INDEX', '修改任意索引', TRUE, 14, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY INDEXTYPE', '修改任意索引类型', TRUE, 15, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY LIBRARY', '修改任意库', TRUE, 16, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY MATERIALIZED VIEW', '修改任意物化视图', TRUE, 17, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY MINING MODEL', '修改任意挖掘模型', TRUE, 18, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY OPERATOR', '修改任意操作符', TRUE, 19, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY OUTLINE', '修改任意大纲', TRUE, 20, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY PROCEDURE', '修改任意存储过程', TRUE, 21, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY ROLE', '修改任意角色', TRUE, 22, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY RULE', '修改任意规则', TRUE, 23, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY RULE SET', '修改任意规则集', TRUE, 24, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY SEQUENCE', '修改任意序列', TRUE, 25, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY SQL PROFILE', '修改任意SQL配置文件', TRUE, 26, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY TABLE', '修改任意表', TRUE, 27, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY TRIGGER', '修改任意触发器', TRUE, 28, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ANY TYPE', '修改任意类型', TRUE, 29, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER DATABASE', '修改数据库', TRUE, 30, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER PROFILE', '修改配置文件', TRUE, 31, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER RESOURCE COST', '修改资源成本', TRUE, 32, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER ROLLBACK SEGMENT', '修改回滚段', TRUE, 33, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER SESSION', '修改会话', TRUE, 34, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER SYSTEM', '修改系统', TRUE, 35, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER TABLESPACE', '修改表空间', TRUE, 36, NOW(), NOW()),
('oracle', 'system_privileges', 'ALTER USER', '修改用户', TRUE, 37, NOW(), NOW()),
('oracle', 'system_privileges', 'ANALYZE ANY', '分析任意对象', TRUE, 38, NOW(), NOW()),
('oracle', 'system_privileges', 'AUDIT ANY', '审计任意对象', TRUE, 39, NOW(), NOW()),
('oracle', 'system_privileges', 'AUDIT SYSTEM', '审计系统', TRUE, 40, NOW(), NOW()),
('oracle', 'system_privileges', 'BACKUP ANY TABLE', '备份任意表', TRUE, 41, NOW(), NOW()),
('oracle', 'system_privileges', 'BECOME USER', '成为用户', TRUE, 42, NOW(), NOW()),
('oracle', 'system_privileges', 'CHANGE NOTIFICATION', '变更通知', TRUE, 43, NOW(), NOW()),
('oracle', 'system_privileges', 'COMMENT ANY MINING MODEL', '注释任意挖掘模型', TRUE, 44, NOW(), NOW()),
('oracle', 'system_privileges', 'COMMENT ANY TABLE', '注释任意表', TRUE, 45, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY ASSEMBLY', '创建任意程序集', TRUE, 46, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY CLUSTER', '创建任意集群', TRUE, 47, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY CONTEXT', '创建任意上下文', TRUE, 48, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY CUBE', '创建任意多维数据集', TRUE, 49, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY CUBE BUILD PROCESS', '创建任意多维数据集构建过程', TRUE, 50, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY CUBE DIMENSION', '创建任意多维数据集维度', TRUE, 51, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY DIMENSION', '创建任意维度', TRUE, 52, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY DIRECTORY', '创建任意目录', TRUE, 53, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY EDITION', '创建任意版本', TRUE, 54, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY EVALUATION CONTEXT', '创建任意评估上下文', TRUE, 55, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY INDEX', '创建任意索引', TRUE, 56, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY INDEXTYPE', '创建任意索引类型', TRUE, 57, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY JOB', '创建任意作业', TRUE, 58, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY LIBRARY', '创建任意库', TRUE, 59, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY MATERIALIZED VIEW', '创建任意物化视图', TRUE, 60, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY MEASURE FOLDER', '创建任意度量文件夹', TRUE, 61, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY MINING MODEL', '创建任意挖掘模型', TRUE, 62, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY OPERATOR', '创建任意操作符', TRUE, 63, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY OUTLINE', '创建任意大纲', TRUE, 64, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY PROCEDURE', '创建任意存储过程', TRUE, 65, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY RULE', '创建任意规则', TRUE, 66, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY RULE SET', '创建任意规则集', TRUE, 67, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY SEQUENCE', '创建任意序列', TRUE, 68, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY SQL PROFILE', '创建任意SQL配置文件', TRUE, 69, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY SYNONYM', '创建任意同义词', TRUE, 70, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY TABLE', '创建任意表', TRUE, 71, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY TRIGGER', '创建任意触发器', TRUE, 72, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY TYPE', '创建任意类型', TRUE, 73, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ANY VIEW', '创建任意视图', TRUE, 74, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ASSEMBLY', '创建程序集', TRUE, 75, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE CLUSTER', '创建集群', TRUE, 76, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE CUBE', '创建多维数据集', TRUE, 77, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE CUBE BUILD PROCESS', '创建多维数据集构建过程', TRUE, 78, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE CUBE DIMENSION', '创建多维数据集维度', TRUE, 79, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE DATABASE LINK', '创建数据库链接', TRUE, 80, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE DIMENSION', '创建维度', TRUE, 81, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE EVALUATION CONTEXT', '创建评估上下文', TRUE, 82, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE EXTERNAL JOB', '创建外部作业', TRUE, 83, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE INDEXTYPE', '创建索引类型', TRUE, 84, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE JOB', '创建作业', TRUE, 85, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE LIBRARY', '创建库', TRUE, 86, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE MATERIALIZED VIEW', '创建物化视图', TRUE, 87, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE MEASURE FOLDER', '创建度量文件夹', TRUE, 88, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE MINING MODEL', '创建挖掘模型', TRUE, 89, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE OPERATOR', '创建操作符', TRUE, 90, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE PROCEDURE', '创建存储过程', TRUE, 91, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE PROFILE', '创建配置文件', TRUE, 92, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE PUBLIC DATABASE LINK', '创建公共数据库链接', TRUE, 93, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ROLE', '创建角色', TRUE, 94, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE ROLLBACK SEGMENT', '创建回滚段', TRUE, 95, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE RULE', '创建规则', TRUE, 96, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE RULE SET', '创建规则集', TRUE, 97, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE SEQUENCE', '创建序列', TRUE, 98, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE SESSION', '创建会话', TRUE, 99, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE SYNONYM', '创建同义词', TRUE, 100, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE TABLE', '创建表', TRUE, 101, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE TABLESPACE', '创建表空间', TRUE, 102, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE TRIGGER', '创建触发器', TRUE, 103, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE TYPE', '创建类型', TRUE, 104, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE USER', '创建用户', TRUE, 105, NOW(), NOW()),
('oracle', 'system_privileges', 'CREATE VIEW', '创建视图', TRUE, 106, NOW(), NOW()),
('oracle', 'system_privileges', 'DEBUG ANY PROCEDURE', '调试任意存储过程', TRUE, 107, NOW(), NOW()),
('oracle', 'system_privileges', 'DEBUG CONNECT SESSION', '调试连接会话', TRUE, 108, NOW(), NOW()),
('oracle', 'system_privileges', 'DELETE ANY CUBE DIMENSION', '删除任意多维数据集维度', TRUE, 109, NOW(), NOW()),
('oracle', 'system_privileges', 'DELETE ANY MEASURE FOLDER', '删除任意度量文件夹', TRUE, 110, NOW(), NOW()),
('oracle', 'system_privileges', 'DELETE ANY TABLE', '删除任意表', TRUE, 111, NOW(), NOW()),
('oracle', 'system_privileges', 'DEQUEUE ANY QUEUE', '出队任意队列', TRUE, 112, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY ASSEMBLY', '删除任意程序集', TRUE, 113, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY CLUSTER', '删除任意集群', TRUE, 114, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY CONTEXT', '删除任意上下文', TRUE, 115, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY CUBE', '删除任意多维数据集', TRUE, 116, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY CUBE BUILD PROCESS', '删除任意多维数据集构建过程', TRUE, 117, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY CUBE DIMENSION', '删除任意多维数据集维度', TRUE, 118, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY DIMENSION', '删除任意维度', TRUE, 119, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY DIRECTORY', '删除任意目录', TRUE, 120, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY EDITION', '删除任意版本', TRUE, 121, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY EVALUATION CONTEXT', '删除任意评估上下文', TRUE, 122, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY INDEX', '删除任意索引', TRUE, 123, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY INDEXTYPE', '删除任意索引类型', TRUE, 124, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY LIBRARY', '删除任意库', TRUE, 125, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY MATERIALIZED VIEW', '删除任意物化视图', TRUE, 126, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY MEASURE FOLDER', '删除任意度量文件夹', TRUE, 127, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY MINING MODEL', '删除任意挖掘模型', TRUE, 128, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY OPERATOR', '删除任意操作符', TRUE, 129, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY OUTLINE', '删除任意大纲', TRUE, 130, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY PROCEDURE', '删除任意存储过程', TRUE, 131, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY ROLE', '删除任意角色', TRUE, 132, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY RULE', '删除任意规则', TRUE, 133, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY RULE SET', '删除任意规则集', TRUE, 134, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY SEQUENCE', '删除任意序列', TRUE, 135, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY SQL PROFILE', '删除任意SQL配置文件', TRUE, 136, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY SYNONYM', '删除任意同义词', TRUE, 137, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY TABLE', '删除任意表', TRUE, 138, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY TRIGGER', '删除任意触发器', TRUE, 139, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY TYPE', '删除任意类型', TRUE, 140, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ANY VIEW', '删除任意视图', TRUE, 141, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP PROFILE', '删除配置文件', TRUE, 142, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP PUBLIC DATABASE LINK', '删除公共数据库链接', TRUE, 143, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP PUBLIC SYNONYM', '删除公共同义词', TRUE, 144, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP ROLLBACK SEGMENT', '删除回滚段', TRUE, 145, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP TABLESPACE', '删除表空间', TRUE, 146, NOW(), NOW()),
('oracle', 'system_privileges', 'DROP USER', '删除用户', TRUE, 147, NOW(), NOW()),
('oracle', 'system_privileges', 'ENQUEUE ANY QUEUE', '入队任意队列', TRUE, 148, NOW(), NOW()),
('oracle', 'system_privileges', 'EXECUTE ANY ASSEMBLY', '执行任意程序集', TRUE, 149, NOW(), NOW()),
('oracle', 'system_privileges', 'EXECUTE ANY CLASS', '执行任意类', TRUE, 150, NOW(), NOW()),
('oracle', 'system_privileges', 'EXECUTE ANY EVALUATION CONTEXT', '执行任意评估上下文', TRUE, 151, NOW(), NOW()),
('oracle', 'system_privileges', 'EXECUTE ANY INDEXTYPE', '执行任意索引类型', TRUE, 152, NOW(), NOW()),
('oracle', 'system_privileges', 'EXECUTE ANY LIBRARY', '执行任意库', TRUE, 153, NOW(), NOW()),
('oracle', 'system_privileges', 'EXECUTE ANY OPERATOR', '执行任意操作符', TRUE, 154, NOW(), NOW()),
('oracle', 'system_privileges', 'EXECUTE ANY PROCEDURE', '执行任意存储过程', TRUE, 155, NOW(), NOW()),
('oracle', 'system_privileges', 'EXECUTE ANY PROGRAM', '执行任意程序', TRUE, 156, NOW(), NOW()),
('oracle', 'system_privileges', 'EXECUTE ANY RULE', '执行任意规则', TRUE, 157, NOW(), NOW()),
('oracle', 'system_privileges', 'EXECUTE ANY RULE SET', '执行任意规则集', TRUE, 158, NOW(), NOW()),
('oracle', 'system_privileges', 'EXECUTE ANY TYPE', '执行任意类型', TRUE, 159, NOW(), NOW()),
('oracle', 'system_privileges', 'EXECUTE ASSEMBLY', '执行程序集', TRUE, 160, NOW(), NOW()),
('oracle', 'system_privileges', 'EXPORT FULL DATABASE', '导出完整数据库', TRUE, 161, NOW(), NOW()),
('oracle', 'system_privileges', 'FLASHBACK ANY TABLE', '闪回任意表', TRUE, 162, NOW(), NOW()),
('oracle', 'system_privileges', 'FLASHBACK ARCHIVE ADMINISTER', '闪回归档管理', TRUE, 163, NOW(), NOW()),
('oracle', 'system_privileges', 'FORCE ANY TRANSACTION', '强制任意事务', TRUE, 164, NOW(), NOW()),
('oracle', 'system_privileges', 'FORCE TRANSACTION', '强制事务', TRUE, 165, NOW(), NOW()),
('oracle', 'system_privileges', 'GLOBAL QUERY REWRITE', '全局查询重写', TRUE, 166, NOW(), NOW()),
('oracle', 'system_privileges', 'GRANT ANY OBJECT PRIVILEGE', '授予任意对象权限', TRUE, 167, NOW(), NOW()),
('oracle', 'system_privileges', 'GRANT ANY PRIVILEGE', '授予任意权限', TRUE, 168, NOW(), NOW()),
('oracle', 'system_privileges', 'GRANT ANY ROLE', '授予任意角色', TRUE, 169, NOW(), NOW()),
('oracle', 'system_privileges', 'IMPORT FULL DATABASE', '导入完整数据库', TRUE, 170, NOW(), NOW()),
('oracle', 'system_privileges', 'INSERT ANY CUBE DIMENSION', '插入任意多维数据集维度', TRUE, 171, NOW(), NOW()),
('oracle', 'system_privileges', 'INSERT ANY MEASURE FOLDER', '插入任意度量文件夹', TRUE, 172, NOW(), NOW()),
('oracle', 'system_privileges', 'INSERT ANY TABLE', '插入任意表', TRUE, 173, NOW(), NOW()),
('oracle', 'system_privileges', 'LOCK ANY TABLE', '锁定任意表', TRUE, 174, NOW(), NOW()),
('oracle', 'system_privileges', 'MANAGE ANY FILE GROUP', '管理任意文件组', TRUE, 175, NOW(), NOW()),
('oracle', 'system_privileges', 'MANAGE ANY QUEUE', '管理任意队列', TRUE, 176, NOW(), NOW()),
('oracle', 'system_privileges', 'MANAGE FILE GROUP', '管理文件组', TRUE, 177, NOW(), NOW()),
('oracle', 'system_privileges', 'MANAGE SCHEDULER', '管理调度器', TRUE, 178, NOW(), NOW()),
('oracle', 'system_privileges', 'MANAGE TABLESPACE', '管理表空间', TRUE, 179, NOW(), NOW()),
('oracle', 'system_privileges', 'MERGE ANY VIEW', '合并任意视图', TRUE, 180, NOW(), NOW()),
('oracle', 'system_privileges', 'ON COMMIT REFRESH', '提交时刷新', TRUE, 181, NOW(), NOW()),
('oracle', 'system_privileges', 'QUERY REWRITE', '查询重写', TRUE, 182, NOW(), NOW()),
('oracle', 'system_privileges', 'READ ANY FILE GROUP', '读取任意文件组', TRUE, 183, NOW(), NOW()),
('oracle', 'system_privileges', 'RESTRICTED SESSION', '受限会话', TRUE, 184, NOW(), NOW()),
('oracle', 'system_privileges', 'RESUMABLE', '可恢复', TRUE, 185, NOW(), NOW()),
('oracle', 'system_privileges', 'SELECT ANY CUBE', '查询任意多维数据集', TRUE, 186, NOW(), NOW()),
('oracle', 'system_privileges', 'SELECT ANY CUBE DIMENSION', '查询任意多维数据集维度', TRUE, 187, NOW(), NOW()),
('oracle', 'system_privileges', 'SELECT ANY MINING MODEL', '查询任意挖掘模型', TRUE, 188, NOW(), NOW()),
('oracle', 'system_privileges', 'SELECT ANY SEQUENCE', '查询任意序列', TRUE, 189, NOW(), NOW()),
('oracle', 'system_privileges', 'SELECT ANY TABLE', '查询任意表', TRUE, 190, NOW(), NOW()),
('oracle', 'system_privileges', 'SELECT ANY TRANSACTION', '查询任意事务', TRUE, 191, NOW(), NOW()),
('oracle', 'system_privileges', 'UNDER ANY TABLE', '任意表下', TRUE, 192, NOW(), NOW()),
('oracle', 'system_privileges', 'UNDER ANY TYPE', '任意类型下', TRUE, 193, NOW(), NOW()),
('oracle', 'system_privileges', 'UNDER ANY VIEW', '任意视图下', TRUE, 194, NOW(), NOW()),
('oracle', 'system_privileges', 'UNLIMITED TABLESPACE', '无限制表空间', TRUE, 195, NOW(), NOW()),
('oracle', 'system_privileges', 'UPDATE ANY CUBE', '更新任意多维数据集', TRUE, 196, NOW(), NOW()),
('oracle', 'system_privileges', 'UPDATE ANY CUBE BUILD PROCESS', '更新任意多维数据集构建过程', TRUE, 197, NOW(), NOW()),
('oracle', 'system_privileges', 'UPDATE ANY CUBE DIMENSION', '更新任意多维数据集维度', TRUE, 198, NOW(), NOW()),
('oracle', 'system_privileges', 'UPDATE ANY TABLE', '更新任意表', TRUE, 199, NOW(), NOW()),

-- tablespace_privileges
('oracle', 'tablespace_privileges', 'ALTER ANY TABLESPACE', '修改任意表空间权限', TRUE, 1, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'ALTER TABLESPACE', '修改表空间权限', TRUE, 2, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'CREATE ANY TABLESPACE', '创建任意表空间权限', TRUE, 3, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'CREATE TABLESPACE', '创建表空间权限', TRUE, 4, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'DEBUG ANY TABLESPACE', '调试任意表空间权限', TRUE, 5, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'DEBUG TABLESPACE', '调试表空间权限', TRUE, 6, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'DROP ANY TABLESPACE', '删除任意表空间权限', TRUE, 7, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'DROP TABLESPACE', '删除表空间权限', TRUE, 8, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'MANAGE ANY TABLESPACE', '管理任意表空间权限', TRUE, 9, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'MANAGE TABLESPACE', '管理表空间权限', TRUE, 10, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'ON COMMIT REFRESH', '提交时刷新权限', TRUE, 11, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'QUERY REWRITE', '查询重写权限', TRUE, 12, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'READ ANY TABLESPACE', '读取任意表空间权限', TRUE, 13, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'READ TABLESPACE', '读取表空间权限', TRUE, 14, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'SELECT ANY TABLESPACE', '查询任意表空间权限', TRUE, 15, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'SELECT TABLESPACE', '查询表空间权限', TRUE, 16, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'UNLIMITED TABLESPACE', '无限制表空间权限', TRUE, 17, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'UPDATE ANY TABLESPACE', '更新任意表空间权限', TRUE, 18, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'UPDATE TABLESPACE', '更新表空间权限', TRUE, 19, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'WRITE ANY TABLESPACE', '写入任意表空间权限', TRUE, 20, NOW(), NOW()),
('oracle', 'tablespace_privileges', 'WRITE TABLESPACE', '写入表空间权限', TRUE, 21, NOW(), NOW()),

-- tablespace_quotas
('oracle', 'tablespace_quotas', 'DEFAULT', '默认配额', TRUE, 1, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'NO QUOTA', '无配额', TRUE, 2, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA', '配额', TRUE, 3, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 100E', '100E配额', TRUE, 4, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 100G', '100G配额', TRUE, 5, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 100K', '100K配额', TRUE, 6, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 100M', '100M配额', TRUE, 7, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 100P', '100P配额', TRUE, 8, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 100T', '100T配额', TRUE, 9, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 10E', '10E配额', TRUE, 10, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 10G', '10G配额', TRUE, 11, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 10K', '10K配额', TRUE, 12, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 10M', '10M配额', TRUE, 13, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 10P', '10P配额', TRUE, 14, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 10T', '10T配额', TRUE, 15, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 1E', '1E配额', TRUE, 16, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 1G', '1G配额', TRUE, 17, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 1K', '1K配额', TRUE, 18, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 1M', '1M配额', TRUE, 19, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 1P', '1P配额', TRUE, 20, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 1T', '1T配额', TRUE, 21, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA UNLIMITED', '无限制配额', TRUE, 22, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 0', '0配额', TRUE, 23, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 5G', '5G配额', TRUE, 24, NOW(), NOW()),
('oracle', 'tablespace_quotas', 'QUOTA 50G', '50G配额', TRUE, 25, NOW(), NOW()),

-- POSTGRESQL权限配置
-- database_privileges
('postgresql', 'database_privileges', 'CONNECT', '连接数据库权限', TRUE, 1, NOW(), NOW()),
('postgresql', 'database_privileges', 'CREATE', '创建对象权限', TRUE, 2, NOW(), NOW()),
('postgresql', 'database_privileges', 'TEMPORARY', '创建临时表权限', TRUE, 3, NOW(), NOW()),
('postgresql', 'database_privileges', 'TEMP', '创建临时表权限（别名）', TRUE, 4, NOW(), NOW()),

-- predefined_roles
('postgresql', 'predefined_roles', 'pg_checkpoint', '检查点角色', TRUE, 1, NOW(), NOW()),
('postgresql', 'predefined_roles', 'pg_database_owner', '数据库所有者角色', TRUE, 2, NOW(), NOW()),
('postgresql', 'predefined_roles', 'pg_execute_server_program', '执行服务器程序角色', TRUE, 3, NOW(), NOW()),
('postgresql', 'predefined_roles', 'pg_monitor', '监控角色', TRUE, 4, NOW(), NOW()),
('postgresql', 'predefined_roles', 'pg_read_all_data', '读取所有数据角色', TRUE, 5, NOW(), NOW()),
('postgresql', 'predefined_roles', 'pg_read_all_settings', '读取所有设置角色', TRUE, 6, NOW(), NOW()),
('postgresql', 'predefined_roles', 'pg_read_all_stats', '读取所有统计信息角色', TRUE, 7, NOW(), NOW()),
('postgresql', 'predefined_roles', 'pg_read_server_files', '读取服务器文件角色', TRUE, 8, NOW(), NOW()),
('postgresql', 'predefined_roles', 'pg_signal_backend', '信号后端角色', TRUE, 9, NOW(), NOW()),
('postgresql', 'predefined_roles', 'pg_stat_scan_tables', '统计扫描表角色', TRUE, 10, NOW(), NOW()),
('postgresql', 'predefined_roles', 'pg_write_all_data', '写入所有数据角色', TRUE, 11, NOW(), NOW()),
('postgresql', 'predefined_roles', 'pg_write_server_files', '写入服务器文件角色', TRUE, 12, NOW(), NOW()),

-- role_attributes
('postgresql', 'role_attributes', 'can_super', '超级用户属性', TRUE, 1, NOW(), NOW()),
('postgresql', 'role_attributes', 'can_create_db', '创建数据库属性', TRUE, 2, NOW(), NOW()),
('postgresql', 'role_attributes', 'can_create_role', '创建角色属性', TRUE, 3, NOW(), NOW()),
('postgresql', 'role_attributes', 'can_inherit', '继承权限属性', TRUE, 4, NOW(), NOW()),
('postgresql', 'role_attributes', 'can_login', '登录属性', TRUE, 5, NOW(), NOW()),
('postgresql', 'role_attributes', 'can_replicate', '复制属性', TRUE, 6, NOW(), NOW()),
('postgresql', 'role_attributes', 'connection_limit', '连接限制属性', TRUE, 7, NOW(), NOW()),
('postgresql', 'role_attributes', 'can_bypass_rls', '绕过行级安全属性', TRUE, 8, NOW(), NOW()),

-- tablespace_privileges
('postgresql', 'tablespace_privileges', 'CREATE', '在表空间中创建对象权限', TRUE, 1, NOW(), NOW()),
('postgresql', 'tablespace_privileges', 'USAGE', '使用表空间权限', TRUE, 2, NOW(), NOW()),

-- SQLSERVER权限配置
-- database_privileges
('sqlserver', 'database_privileges', 'SELECT', '查询数据', TRUE, 1, NOW(), NOW()),
('sqlserver', 'database_privileges', 'INSERT', '插入数据', TRUE, 2, NOW(), NOW()),
('sqlserver', 'database_privileges', 'UPDATE', '更新数据', TRUE, 3, NOW(), NOW()),
('sqlserver', 'database_privileges', 'DELETE', '删除数据', TRUE, 4, NOW(), NOW()),
('sqlserver', 'database_privileges', 'CREATE', '创建对象', TRUE, 5, NOW(), NOW()),
('sqlserver', 'database_privileges', 'ALTER', '修改/删除对象（包含DROP功能）', TRUE, 6, NOW(), NOW()),
('sqlserver', 'database_privileges', 'EXECUTE', '执行存储过程', TRUE, 7, NOW(), NOW()),
('sqlserver', 'database_privileges', 'CONTROL', '完全控制权限', TRUE, 8, NOW(), NOW()),
('sqlserver', 'database_privileges', 'REFERENCES', '引用权限', TRUE, 9, NOW(), NOW()),
('sqlserver', 'database_privileges', 'VIEW DEFINITION', '查看定义', TRUE, 10, NOW(), NOW()),
('sqlserver', 'database_privileges', 'TAKE OWNERSHIP', '获取所有权', TRUE, 11, NOW(), NOW()),
('sqlserver', 'database_privileges', 'IMPERSONATE', '模拟权限', TRUE, 12, NOW(), NOW()),
('sqlserver', 'database_privileges', 'CREATE SCHEMA', '创建架构', TRUE, 13, NOW(), NOW()),
('sqlserver', 'database_privileges', 'ALTER ANY SCHEMA', '修改任意架构', TRUE, 14, NOW(), NOW()),
('sqlserver', 'database_privileges', 'CREATE TABLE', '创建表', TRUE, 15, NOW(), NOW()),
('sqlserver', 'database_privileges', 'CREATE VIEW', '创建视图', TRUE, 16, NOW(), NOW()),
('sqlserver', 'database_privileges', 'CREATE PROCEDURE', '创建存储过程', TRUE, 17, NOW(), NOW()),
('sqlserver', 'database_privileges', 'CREATE FUNCTION', '创建函数', TRUE, 18, NOW(), NOW()),
('sqlserver', 'database_privileges', 'CREATE TRIGGER', '创建触发器', TRUE, 19, NOW(), NOW()),

-- database_roles
('sqlserver', 'database_roles', 'db_owner', '数据库所有者', TRUE, 1, NOW(), NOW()),
('sqlserver', 'database_roles', 'db_accessadmin', '访问管理员', TRUE, 2, NOW(), NOW()),
('sqlserver', 'database_roles', 'db_securityadmin', '安全管理员', TRUE, 3, NOW(), NOW()),
('sqlserver', 'database_roles', 'db_ddladmin', 'DDL管理员', TRUE, 4, NOW(), NOW()),
('sqlserver', 'database_roles', 'db_backupoperator', '备份操作员', TRUE, 5, NOW(), NOW()),
('sqlserver', 'database_roles', 'db_datareader', '数据读取者', TRUE, 6, NOW(), NOW()),
('sqlserver', 'database_roles', 'db_datawriter', '数据写入者', TRUE, 7, NOW(), NOW()),
('sqlserver', 'database_roles', 'db_denydatareader', '拒绝数据读取', TRUE, 8, NOW(), NOW()),
('sqlserver', 'database_roles', 'db_denydatawriter', '拒绝数据写入', TRUE, 9, NOW(), NOW()),

-- server_permissions
('sqlserver', 'server_permissions', 'CONTROL SERVER', '控制服务器', TRUE, 1, NOW(), NOW()),
('sqlserver', 'server_permissions', 'ALTER ANY LOGIN', '修改任意登录', TRUE, 2, NOW(), NOW()),
('sqlserver', 'server_permissions', 'ALTER ANY SERVER ROLE', '修改任意服务器角色', TRUE, 3, NOW(), NOW()),
('sqlserver', 'server_permissions', 'CREATE ANY DATABASE', '创建任意数据库', TRUE, 4, NOW(), NOW()),
('sqlserver', 'server_permissions', 'ALTER ANY DATABASE', '修改任意数据库', TRUE, 5, NOW(), NOW()),
('sqlserver', 'server_permissions', 'VIEW SERVER STATE', '查看服务器状态', TRUE, 6, NOW(), NOW()),
('sqlserver', 'server_permissions', 'ALTER SERVER STATE', '修改服务器状态', TRUE, 7, NOW(), NOW()),
('sqlserver', 'server_permissions', 'ALTER SETTINGS', '修改设置', TRUE, 8, NOW(), NOW()),
('sqlserver', 'server_permissions', 'ALTER TRACE', '修改跟踪', TRUE, 9, NOW(), NOW()),
('sqlserver', 'server_permissions', 'AUTHENTICATE SERVER', '服务器身份验证', TRUE, 10, NOW(), NOW()),
('sqlserver', 'server_permissions', 'BACKUP DATABASE', '备份数据库', TRUE, 11, NOW(), NOW()),
('sqlserver', 'server_permissions', 'BACKUP LOG', '备份日志', TRUE, 12, NOW(), NOW()),
('sqlserver', 'server_permissions', 'CHECKPOINT', '检查点', TRUE, 13, NOW(), NOW()),
('sqlserver', 'server_permissions', 'CONNECT SQL', '连接SQL', TRUE, 14, NOW(), NOW()),
('sqlserver', 'server_permissions', 'SHUTDOWN', '关闭服务器', TRUE, 15, NOW(), NOW()),
('sqlserver', 'server_permissions', 'IMPERSONATE ANY LOGIN', '模拟任意登录', TRUE, 16, NOW(), NOW()),
('sqlserver', 'server_permissions', 'VIEW ANY DEFINITION', '查看任意定义', TRUE, 17, NOW(), NOW()),
('sqlserver', 'server_permissions', 'VIEW ANY COLUMN ENCRYPTION KEY DEFINITION', '查看任意列加密密钥定义', TRUE, 18, NOW(), NOW()),
('sqlserver', 'server_permissions', 'VIEW ANY COLUMN MASTER KEY DEFINITION', '查看任意列主密钥定义', TRUE, 19, NOW(), NOW()),

-- server_roles
('sqlserver', 'server_roles', 'sysadmin', '系统管理员', TRUE, 1, NOW(), NOW()),
('sqlserver', 'server_roles', 'serveradmin', '服务器管理员', TRUE, 2, NOW(), NOW()),
('sqlserver', 'server_roles', 'securityadmin', '安全管理员', TRUE, 3, NOW(), NOW()),
('sqlserver', 'server_roles', 'processadmin', '进程管理员', TRUE, 4, NOW(), NOW()),
('sqlserver', 'server_roles', 'setupadmin', '设置管理员', TRUE, 5, NOW(), NOW()),
('sqlserver', 'server_roles', 'bulkadmin', '批量操作管理员', TRUE, 6, NOW(), NOW()),
('sqlserver', 'server_roles', 'diskadmin', '磁盘管理员', TRUE, 7, NOW(), NOW()),
('sqlserver', 'server_roles', 'dbcreator', '数据库创建者', TRUE, 8, NOW(), NOW()),
('sqlserver', 'server_roles', 'public', '公共角色', TRUE, 9, NOW(), NOW())
ON CONFLICT (db_type, category, permission_name) DO NOTHING;
