"""集中存放项目级别的类型别名与协议.

聚合资源层常用的类型别名,避免各模块重复定义以致类型漂移.
"""

from app.core.types.accounts import PermissionSnapshot, RawAccount, RemoteAccount
from app.core.types.classification import ClassificationEngineResult, RuleExpression
from app.core.types.dbapi import DBAPIConnection, DBAPICursor
from app.core.types.query_protocols import QueryProtocol
from app.core.types.resources import (
    ResourceContext,
    ResourceIdentifier,
    ResourceInstance,
    ResourcePayload,
    SupportsResourceId,
    TemplateContext,
)
from app.core.types.structures import (
    CategoryOptionDict,
    ColorHex,
    ColorName,
    ColorOptionDict,
    ColorToken,
    ContextDict,
    ContextMapping,
    ContextValue,
    CssClassName,
    FormErrorMapping,
    JsonDict,
    JsonValue,
    LoggerExtra,
    LoggerProtocol,
    MutablePayloadDict,
    NumericLike,
    PayloadMapping,
    PayloadValue,
    RouteSafetyOptions,
    StructlogEventDict,
)
from app.core.types.sync import (
    CollectionSummary,
    DiffEntry,
    InventorySummary,
    OtherDiffEntry,
    PermissionDiffPayload,
    PrivilegeDiffEntry,
    RemoteAccountMap,
    SyncConnection,
    SyncOperationResult,
    SyncStagesSummary,
    SyncSummary,
)

__all__ = [
    "CategoryOptionDict",
    "ClassificationEngineResult",
    "CollectionSummary",
    "ColorHex",
    "ColorName",
    "ColorOptionDict",
    "ColorToken",
    "ContextDict",
    "ContextMapping",
    "ContextValue",
    "CssClassName",
    "DBAPIConnection",
    "DBAPICursor",
    "DiffEntry",
    "FormErrorMapping",
    "InventorySummary",
    "JsonDict",
    "JsonValue",
    "LoggerExtra",
    "LoggerProtocol",
    "MutablePayloadDict",
    "NumericLike",
    "OtherDiffEntry",
    "PayloadMapping",
    "PayloadValue",
    "PermissionDiffPayload",
    "PermissionSnapshot",
    "PrivilegeDiffEntry",
    "QueryProtocol",
    "RawAccount",
    "RemoteAccount",
    "RemoteAccountMap",
    "ResourceContext",
    "ResourceIdentifier",
    "ResourceInstance",
    "ResourcePayload",
    "RouteSafetyOptions",
    "RuleExpression",
    "StructlogEventDict",
    "SupportsResourceId",
    "SyncConnection",
    "SyncOperationResult",
    "SyncStagesSummary",
    "SyncSummary",
    "TemplateContext",
]
