from __future__ import annotations

from collections.abc import Callable
from contextlib import AbstractContextManager
from typing import Any, Generic, NoReturn, TypeVar, overload

_T = TypeVar("_T")

class _MarkDecorator:
    def __getattr__(self, name: str) -> _MarkDecorator: ...
    def __call__(self, obj: Callable[..., _T]) -> _T: ...

mark: _MarkDecorator

def fail(message: str | None = ...) -> NoReturn: ...

class ExceptionInfo(Generic[_T]):
    value: _T

def raises(
    expected_exception: type[_T], *, match: str | None = ..., **kwargs: Any
) -> AbstractContextManager[ExceptionInfo[_T]]: ...
@overload
def fixture(func: Callable[..., _T]) -> Callable[..., _T]: ...
@overload
def fixture(*, scope: str | None = ..., **kwargs: Any) -> Callable[[Callable[..., _T]], Callable[..., _T]]: ...
def skip(reason: str | None = ..., *, allow_module_level: bool = ..., **kwargs: Any) -> NoReturn: ...

class MonkeyPatch:
    def setattr(self, target: object, name: str, value: object, raising: bool = ...) -> None: ...
    def setenv(self, name: str, value: str) -> None: ...
    def delenv(self, name: str, raising: bool = ...) -> None: ...
    def chdir(self, path: str) -> None: ...
    def syspath_prepend(self, path: str) -> None: ...
